export const projects = [
	{
		image: 'assets/ai-dengue-preview.png',
		imageAlt: 'AI Dengue Project Preview',
		category: 'Machine Learning • Web App',
		title: 'AI-Based Dengue Hotspot Predictor',
		description: 'Machine Learning Powered Dengue Hotspot Prediction and Geospatial Monitoring Dashboard for Public Health Management.',
		tags: ['AI', 'DJANGO', 'PYTHON', 'JS', 'API'],
		github: 'https://github.com/upsetDokkaebi/AI-Based-Dengue-Hotspot-Predictor-Django',
		liveDemo: '',
	},
	{
		image: 'assets/jump-over-villager-preview.png',
		imageAlt: 'Projects preview 2',
		category: 'Game Development • Web App',
		title: 'Jump Over Villager',
		description: 'A lightweight browser game inspired by endless runners and Minecraft-style visuals.',
		tags: ['HTML', 'CSS', 'JS'],
		github: 'https://github.com/upsetDokkaebi/jump-over-villager_webgame',
		liveDemo: 'https://jump-over-villager.vercel.app/',
	},
	{
		image: 'assets/queuing-preview.png',
		imageAlt: 'Queuing Project Preview',
		category: 'Product • Backend',
		title: 'Service Queuing System',
		description: 'A web-based queue management system that allows users to take queue numbers, monitor their position, and helps staff manage and process customers in an organized manner.',
		tags: ['HTML', 'CSS', 'JS'],
		github: 'https://github.com/upsetDokkaebi/queuing-system',
		liveDemo: 'https://public-queuing-system.vercel.app/display.html',
	},
	{
		image: 'assets/invpos-preview.png',
		imageAlt: 'Invpos Project Preview',
		category: 'Product • Web App',
		title: 'Harvest POS & Inventory Management System',
		description: 'A comprehensive point-of-sale and inventory management system designed for small businesses.',
		tags: ['REACT', 'CSS', 'NODE', 'SUPABASE'],
		github: 'https://github.com/upsetDokkaebi/InvPOS',
		liveDemo: 'https://mini-invpos.vercel.app/',
	},
	{
		image: 'assets/abyssal-guild-preview.png',
		imageAlt: 'Abyssal Guild Project Preview',
		category: 'Product • Web Design',
		title: 'Abyssal Guild',
		description: 'Abyssal Guild is a web design focused on creating an MMORPG-themed with interactive animations and a fantasy guild atmosphere.',
		tags: ['HTML', 'CSS', 'JS'],
		github: 'https://github.com/upsetDokkaebi/abyssal-guild-web-design',
		liveDemo: 'https://abyssal-guild.vercel.app/',
	},
	{
		image: 'assets/cmu-lms-preview.png',
		imageAlt: 'CMU LMS Project Preview',
		category: 'Product • Web Design',
		title: 'CMU LMS',
		description: 'A comprehensive learning management system designed for educational institutions to facilitate online learning and course management.',
		tags: ['HTML', 'CSS', 'JS'],
		github: 'https://github.com/upsetDokkaebi/cmu-lms-web-design',
		liveDemo: 'https://cmu-lms-static.vercel.app/',
	},
];
